### ISSUE TITLE
Domain Path Alias Triggers Page Not Found

### ISSUE THREAD

**Issue by matthandus** [Adyax/domain_path#2]
Hi @skrasulevskiy ,

Thank you for working on this module! It's the last use case I need covered on an upcoming website project.

I installed this Domain Path module in my prototype site using Domain alpha13. I also have Language enabled. And, Pathauto. I don't need this module to work with Pathatuo... but I do need it to work with Language. Just FYI.

The install is clean. There's no errors. I create some Domain Paths while creating new content. No errors.

But, as soon as the content is posted, there's no way to view the page using the new alias. It says Page Not Found.

What more info do you need?

**Comment by matthandus** [comment]
Hi again @skrasulevskiy !

Happy dance! I uninstalled PathAuto and Domain Path just WORKS! Bravo!!

Is there anything I can do to help?

**Comment by skrasulevskiy** [comment]
Hello @matthandus!
Thanks for info!
